embed_assets: off
gzip_assets: off
compress_assets: on
package_path: assets
javascript_compressor: uglifier

javascripts:
  site:
    - public/js/lib/zepto.min.js
    - public/js/app.js

stylesheets:
  site:
    - public/css/defaults.css
    - public/css/app.css
